### ISSUE TITLE
Tracking issue for `Time` Component

### ISSUE THREAD

**Issue by nekevss** [boa-dev/temporal#10]
Below is the functionality needed for the `Time` component according to the `Temporal` specification.

- [x] 4.3.3 get `Temporal.PlainTime.prototype.hour`
- [x] 4.3.4 get `Temporal.PlainTime.prototype.minute`
- [x] 4.3.5 get `Temporal.PlainTime.prototype.second`
- [x] 4.3.6 get `Temporal.PlainTime.prototype.millisecond`
- [x] 4.3.7 get `Temporal.PlainTime.prototype.microsecond`
- [x] 4.3.8 get `Temporal.PlainTime.prototype.nanosecond`
- [x] 4.3.9 `Temporal.PlainTime.prototype.add ( temporalDurationLike )`
- [x] 4.3.10 `Temporal.PlainTime.prototype.subtract ( temporalDurationLike )`
- [x] 4.3.11 `Temporal.PlainTime.prototype.with ( temporalTimeLike [ , options ] )`
- [x] 4.3.12 `Temporal.PlainTime.prototype.until ( other [ , options ] )`
- [x] 4.3.13 `Temporal.PlainTime.prototype.since ( other [ , options ] )`
- [x] 4.3.14 `Temporal.PlainTime.prototype.round ( roundTo )`
- [x] 4.3.15 `Temporal.PlainTime.prototype.equals ( other )`
- [x] ~~4.3.16 `Temporal.PlainTime.prototype.toPlainDateTime ( temporalDate )`~~ REMOVED
- [x] ~~4.3.17 `Temporal.PlainTime.prototype.toZonedDateTime ( item )`~~ REMOVED
- [x] ~~4.3.18 `Temporal.PlainTime.prototype.getISOFields ( )`~~ REMOVED
- [x] 4.3.19 `Temporal.PlainTime.prototype.toString ( [ options ] )`
- [x] ~~4.3.20 `Temporal.PlainTime.prototype.toLocaleString ( [ locales [ , options ] ] )`~~ DEFERRED
- [x] 4.3.21 `Temporal.PlainTime.prototype.toJSON ( )` ENGINE SPECIFIC
- [x] 4.3.22 `Temporal.PlainTime.prototype.valueOf ( )` ENGINE SPECIFIC

**Comment by nekevss** [comment]
Initial work on PlainTime implementation completed.
