### ISSUE TITLE
Tracking issue for `Duration` component

### ISSUE THREAD

**Issue by nekevss** [boa-dev/temporal#11]
Below is the functionality needed for the `Duration` component.

- [x] 7.3.3 get `Temporal.Duration.prototype.years`
- [x] 7.3.4 get `Temporal.Duration.prototype.months`
- [x] 7.3.5 get `Temporal.Duration.prototype.weeks`
- [x] 7.3.6 get `Temporal.Duration.prototype.days`
- [x] 7.3.7 get `Temporal.Duration.prototype.hours`
- [x] 7.3.8 get `Temporal.Duration.prototype.minutes`
- [x] 7.3.9 get `Temporal.Duration.prototype.seconds`
- [x] 7.3.10 get `Temporal.Duration.prototype.milliseconds`
- [x] 7.3.11 get `Temporal.Duration.prototype.microseconds`
- [x] 7.3.12 get `Temporal.Duration.prototype.nanoseconds`
- [x] 7.3.13 get `Temporal.Duration.prototype.sign`
- [x] 7.3.14 get `Temporal.Duration.prototype.blank` (implemented as `is_zero`)
- [x] 7.3.15 `Temporal.Duration.prototype.with ( temporalDurationLike )`
- [x] 7.3.16 `Temporal.Duration.prototype.negated ( )`
- [x] 7.3.17 `Temporal.Duration.prototype.abs ( )`
- [x] 7.3.18 `Temporal.Duration.prototype.add ( other [ , options ] )`
- [x] 7.3.19 `Temporal.Duration.prototype.subtract ( other [ , options ] )`
- [x] 7.3.20 `Temporal.Duration.prototype.round ( roundTo )`
- [x] 7.3.21 `Temporal.Duration.prototype.total ( totalOf )`
- [x] 7.3.22 `Temporal.Duration.prototype.toString ( [ options ] )`
- [x] 7.3.23 `Temporal.Duration.prototype.toJSON ( )`
- [x] 7.3.24 `Temporal.Duration.prototype.toLocaleString ( [ locales [ , options ] ] )` (not yet implementable - needs `icu_duration` if it were to exist)
- [x] 7.3.25 `Temporal.Duration.prototype.valueOf ( )`

**Comment by nekevss** [comment]
This has long been "done", but I've left open for a couple reasons:

1. the inner representation of Duration can still be optimized
2. there is a known precision bug on maximum milliseconds, microseconds, and nanoseconds.

These won't necessarily impact a 0.1 release as the fixes for the two above issues would be internal. So I'm marking this closed considering that.
